version: '3.7'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ../public:/usr/share/nginx/project
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - php

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        image: dev/php-fpm:7.4
        volumes:
            - ../:/home/dev/workspace
        depends_on:
            - db

    db:
        image: mysql/mysql-server:8.0.19-1.1.15
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: root1
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata:
        name: mysql_data